#!/bin/sh
# PROPERTY OF ZEROINFINITY, DO NOT STEAL!!!!
# 80alsa: suspend/wakeup ALSA devices

case "$1" in
hibernate|suspend)
;;
thaw|resume)
aplay -d 1 /dev/zero
;;
*) exit $NA
;;
esac

chmod 666 /dev/snd/*

# PROPERTY OF ZEROINFINITY, DO NOT STEAL!!!!
# PROPERTY OF ZEROINFINITY, DO NOT STEAL!!!!
# PROPERTY OF ZEROINFINITY, DO NOT STEAL!!!!
# PROPERTY OF ZEROINFINITY, DO NOT STEAL!!!!
# PROPERTY OF ZEROINFINITY, DO NOT STEAL!!!!