#!/system/bin/sh

#
setprop ro.config.hw_dts true
setprop use.dts_m6 true
setprop use.dts_m6_notify true
setprop use.dts_eagle true
setprop persist.audio.hifi.int_codec true
setprop audio.offload.pcm.16bit.enable true
setprop audio.offload.pcm.24bit.enable true
setprop audio.offload.track.enabled true
setprop audio.deep_buffer.media false
setprop tunnel.audiovideo.decode false
setprop persist.sys.media.use-awesome 1
setprop af.resampler.quality 255
setprop persist.af.resampler.quality 255
setprop persist.dev.pm.dyn_samplingrate 1
setprop ro.sound.driver alsa
setprop ro.sound.alsa snd_pcm
setprop AUDIODRIVER alsa
setprop ro.sound.driver alsa
setprop clock.allow_streaming_errors false
setprop default.pcm.rate_converter samplerate_zero_order
setprop ro.ril.enable.amr.wideband 1
setprop tunnel.decode false
setprop lpa.decode false
setprop lpa.releaselock false
setprop lpa.use-stagefright false
setprop ro.lenovo.hifi_support true
#

LOG_FILE=/data/local/biohazard_setprop_run.log;

if [ -e /data/local/biohazard_setprop_run.log ];
then
    rm /data/local/biohazard_setprop_run.log
fi

echo "biohazard_setprop has run successfully $(date +"%m-%d-%Y %H:%M:%S")" | tee -a $LOG_FILE;
